### ISSUE TITLE
运行pipeline java报错，是需要fastq文件内容或者gtf内容有要求

### ISSUE THREAD

**Issue by DooYal** [bioinfo-biols/CIRI-full#4]
报错log如下
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: Range [2, 150) out of bounds for length 141
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55)
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:112)
	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:349)
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4865)
	at java.base/java.lang.String.substring(String.java:2834)
	at index_head_finder_more.<init>(index_head_finder_more.java:45)
	at RO1_single.getro1(RO1_single.java:81)
	at CIRI_Full2.main(CIRI_Full2.java:228)

#输入命令
java -jar ~/program/CIRI-full/bin/CIRI-Full_v2.1.2.jar Pipeline -1 $out_prefix.rmrrna.fastq.1.gz -2 $out_prefix.rmrrna.fastq.2.gz \
																-d $out_prefix.cirifull/ -o $sample \
																-r $ref_fas -a $ref_gtf -t 4
#参考序列为GRCh38.p14.fasta，gtf为GENECODE.v44.annotation.gtf

**Comment by Kevinzjy** [comment]
CIRI-full不支持trim之后的fastq，需要改成原始的pe150 reads

**Comment by DooYal** [comment]
> CIRI-full不支持trim之后的fastq，需要改成原始的pe150 reads
好的，谢谢，再想请教一下，如果是ribo-profiling常用的单端测序也不能用CIRI-full了吧

**Comment by Kevinzjy** [comment]
> 好的，谢谢，再想请教一下，如果是ribo-profiling常用的单端测序也不能用CIRI-full了吧

是的，CIRI-full不支持单端数据。可以直接用我们的CIRI2工具预测环形RNA，但是没法预测环形RNA的内部结构

**Comment by DooYal** [comment]
> > 好的，谢谢，再想请教一下，如果是ribo-profiling常用的单端测序也不能用CIRI-full了吧
> 
> 是的，CIRI-full不支持单端数据。可以直接用我们的CIRI2工具预测环形RNA，但是没法预测环形RNA的内部结构

好的，多谢指教

**Comment by DooYal** [comment]
不好意思，又存在新的java报错，这回是运行CIRI-vis.jar，没有分析数据，直接-h查看文档也报错
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/batik/svggen/SVGGraphics2D
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:534)
	at java.base/java.lang.Class.forName(Class.java:513)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:56)
Caused by: java.lang.ClassNotFoundException: org.apache.batik.svggen.SVGGraphics2D
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 4 more
我装了这个batik库也配置了环境变量，但是还是这种报错

**Comment by DooYal** [comment]
老师，您好，我之前还发邮件问赵老师关于注释正负链矛盾的问题，但是至今

> > 好的，谢谢，再想请教一下，如果是ribo-profiling常用的单端测序也不能用CIRI-full了吧
> 
> 是的，CIRI-full不支持单端数据。可以直接用我们的CIRI2工具预测环形RNA，但是没法预测环形RNA的内部结构

老师，您好，我之前还发邮件问赵老师关于注释正负链矛盾的问题，但是至今没回复，所以想在这里请教您一下这个问题，
![image](https://github.com/bioinfo-biols/CIRI-full/assets/31724229/bb8d598f-97f2-417e-a24d-c95cb98b5ef0)
![image](https://github.com/bioinfo-biols/CIRI-full/assets/31724229/dbc1dbc5-edfa-46ac-a81d-e8c3f8980d0b)
![image](https://github.com/bioinfo-biols/CIRI-full/assets/31724229/22e265c3-e4b8-496b-9e5f-cb2958a0ac0b)

**Comment by Kevinzjy** [comment]
网页上提供的序列可能有误，一般按照软件给出的链信息为准

**Comment by DooYal** [comment]
> 网页上提供的序列可能有误，一般按照软件给出的链信息为准

好的，谢谢

**Comment by ChristopherLeeZG** [comment]
> CIRI-full不支持trim之后的fastq，需要改成原始的pe150 reads

老师您好，CIRI-full不支持trim之后的序列，请问其他几个软件支持吗。我已经发表的paper里有用到CIRI2，但用的是trim后的fastq
CIRI2
CIRI-AS
CIRI-vis
CIRIquant
CIRI-long
感谢老师帮助！
